apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: aloha15
  region: us-west-2
  version: "1.27"

managedNodeGroups:
  - name: aloha15-one
    instanceType: t3.medium
    amiFamily: AmazonLinux2
    minSize: 1
    desiredCapacity: 2
    maxSize: 3
    volumeSize: 100
    volumeType: gp3
    volumeEncrypted: true

kubernetesNetworkConfig:
  ipFamily: IPv4

addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy

iam:
  withOIDC: true
